workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/mlops-exercises-484210/eurosat/gpu_cloud_storage_and_saving:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_PROJECT
          value: mlops-project
        - name: WANDB_ENTITY
          value: s252840-danmarks-tekniske-universitet-dtu
        - name: HYDRA_FULL_ERROR
          value: "1"
